#!usr/bin/env python3.6
__author__ = "X Zhang"
__email__ = "xzhang@westwoodrobotics.net"
__copyright__ = "Copyright 2020 Westwood Robotics Corp."
__date__ = "Feb 14, 2020"
__version__ = "0.1.0"
__status__ = "Beta"

'''
CONTROL_TABLE for Dynamixel X series actuator
'''
# Unit
POSITION_UNIT = 0.00153398078  # radian/value
VELOCITY_UNIT = 0.02398082392  # (radian/s)/value  0.229 rpm

# Control table address
# EEPROM
ADDR_X_ID = 7
ADDR_X_BAUDRATE = 8
ADDR_X_DRIVE_MODE = 10
ADDR_X_MODE = 11
ADDR_X_HOMING_OFFSET = 20
ADDR_X_VELOCITY_LIMIT = 44
ADDR_X_POSITION_LIMIT_MAX = 48
ADDR_X_POSITION_LIMIT_MIN = 52

# RAM
ADDR_X_TORQUE_ENABLE = 64  # Control table address is different in Dynamixel model
ADDR_X_P_GAIN_VELOCITY = 76
ADDR_X_I_GAIN_VELOCITY = 78
ADDR_X_P_GAIN_POSITION = 84
ADDR_X_I_GAIN_POSITION = 82
ADDR_X_D_GAIN_POSITION = 80
ADDR_X_1ST_GAIN_FEEDFORWARD = 90
ADDR_X_2ND_GAIN_FEEDFORWARD = 88
ADDR_X_GOAL_POSITION = 116
ADDR_X_GOAL_VELOCITY = 104
ADDR_X_PRESENT_POSITION = 132
ADDR_X_PRESENT_VELOCITY = 128
ADDR_X_PROFILE_VELOCITY = 112
ADDR_X_PROFILE_ACCELERATION = 108
ADDR_X_PRESENT_LOAD = 126
